#!/usr/bin/env node
/**
 * 扫描 src/cases/<dir>/index.ts，自动生成 src/cases/manifest.ts（案例元数据 + 惰性组件加载器）。
 *
 * 规则：
 * - 案例目录 = src/cases 下含 index.ts 且目录名不以 `-lib` 结尾的目录；
 * - 元数据字段（id/title/category/description/tag/updatedAt）从 default export 对象字面量提取；
 * - `available` 表示该案例是否声明了 `component`；
 * - icon 通过 alias 在 import 声明中反查资源路径（./icon.webp 等），生成静态 import 交给 Vite 处理；
 * - 条目顺序：优先沿用已生成 manifest.ts 的顺序，其次沿用旧 src/cases/index.ts 的 demos 数组顺序，新发现的案例追加到末尾。
 *
 * 运行方式：npm run sync
 */
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import ts from 'typescript'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const casesRoot = join(root, 'src/cases')
const manifestPath = join(casesRoot, 'manifest.ts')
const indexPath = join(casesRoot, 'index.ts')
const header = `// AUTO-GENERATED by scripts/sync-cases.mjs — DO NOT EDIT MANUALLY.
// Run \`npm run sync\` to regenerate after adding / removing a case directory.
/* eslint-disable */

`

const textOf = (node) =>
  ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node) ? node.text : null

function literalProps(source) {
  const sf = ts.createSourceFile('x.ts', source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS)
  const imports = {}
  const decls = {}
  for (const st of sf.statements) {
    if (ts.isImportDeclaration(st) && ts.isStringLiteral(st.moduleSpecifier)) {
      const src = st.moduleSpecifier.text
      for (const cl of st.importClause?.namedBindings && ts.isNamedImports(st.importClause.namedBindings)
        ? st.importClause.namedBindings.elements
        : []) {
        imports[cl.name.text] = src
      }
      if (st.importClause?.name) imports[st.importClause.name.text] = src
    } else if (ts.isVariableStatement(st)) {
      for (const d of st.declarationList.declarations) {
        if (ts.isIdentifier(d.name)) decls[d.name.text] = d.initializer
      }
    }
  }
  let obj = null
  for (const st of sf.statements) {
    if (ts.isExportAssignment(st) && !st.isExportEquals) {
      let expr = st.expression
      if (ts.isAsExpression(expr)) expr = expr.expression
      if (ts.isObjectLiteralExpression(expr)) obj = expr
      else if (ts.isIdentifier(expr) && decls[expr.text]) {
        let init = decls[expr.text]
        if (ts.isAsExpression(init)) init = init.expression
        if (ts.isObjectLiteralExpression(init)) obj = init
      }
    }
  }
  const iconAliases = new Set(
    Object.entries(imports)
      .filter(([, src]) => /\.(webp|png|jpe?g|gif|svg)$/.test(src))
      .map(([alias]) => alias)
  )
  const props = { icon: undefined, available: false }
  if (obj) {
    for (const p of obj.properties) {
      const key = p.name ? p.name.text ?? p.name.getText(sf).replace(/['"]/g, '') : null
      if (!key) continue
      if (key === 'component') {
        props.available = true
        continue
      }
      let init = null
      if (ts.isPropertyAssignment(p)) init = p.initializer
      else if (ts.isShorthandPropertyAssignment(p)) init = p.name
      if (!init) continue
      const txt = textOf(init)
      if (txt !== null) {
        props[key] = txt
      } else if (ts.isIdentifier(init) && iconAliases.has(init.text) && props.icon === undefined) {
        props.icon = imports[init.text]
      }
    }
  }
  return props
}

function orderFromExistingManifest() {
  try {
    const src = readFileSync(manifestPath, 'utf8')
    return [...src.matchAll(/^\s*\{\s*id:\s*'([\w-]+)'/gm)].map((m) => m[1])
  } catch {
    return []
  }
}

function orderFromLegacyIndex() {
  const src = readFileSync(indexPath, 'utf8')
  const sf = ts.createSourceFile('index.ts', src, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS)
  const aliasDir = {}
  const order = []
  for (const st of sf.statements) {
    if (ts.isImportDeclaration(st) && ts.isStringLiteral(st.moduleSpecifier)) {
      const srcPath = st.moduleSpecifier.text
      if (!srcPath.startsWith('./') || srcPath.slice(2).includes('/')) continue
      const name = st.importClause?.name
      if (name) aliasDir[name.text] = srcPath.slice(2)
    }
  }
  for (const st of sf.statements) {
    if (!ts.isVariableStatement(st)) continue
    for (const d of st.declarationList.declarations) {
      if (!ts.isIdentifier(d.name) || d.name.text !== 'demos') continue
      const arr = d.initializer
      if (arr && ts.isArrayLiteralExpression(arr)) {
        for (const el of arr.elements) {
          if (ts.isIdentifier(el) && aliasDir[el.text]) order.push(aliasDir[el.text])
        }
      }
    }
  }
  return order
}

const dirs = readdirSync(casesRoot)
  .filter((d) => {
    try {
      return statSync(join(casesRoot, d)).isDirectory()
    } catch {
      return false
    }
  })
  .filter((d) => !d.endsWith('-lib'))
  .filter((d) => {
    try {
      statSync(join(casesRoot, d, 'index.ts'))
      return true
    } catch {
      return false
    }
  })

const preferred = orderFromExistingManifest().length
  ? orderFromExistingManifest()
  : orderFromLegacyIndex()
const ordered = []
for (const d of preferred) if (dirs.includes(d)) ordered.push(d)
for (const d of dirs) if (!ordered.includes(d)) ordered.push(d)

const iconImports = []
const loaderLines = []
const metaLines = []
const warnings = []
for (const d of ordered) {
  const source = readFileSync(join(casesRoot, d, 'index.ts'), 'utf8')
  const props = literalProps(source)
  const id = props.id ?? d
  if (id !== d) warnings.push(`[warn] ${d}: id (${id}) differs from directory name`)
  if (!props.title || !props.category) warnings.push(`[warn] ${d}: missing title/category`)

  if (props.icon) {
    const alias = `icon_${d.replace(/[^\w]/g, '_')}`
    iconImports.push(`import ${alias} from './${d}/${props.icon.replace(/^\.\//, '')}'`)
    props.iconAlias = alias
  }
  loaderLines.push(`  '${id}': () => import('./${d}/index.ts'),`)

  const item = {
    id,
    title: props.title ?? d,
    category: props.category ?? 'scene',
    description: props.description ?? '',
    tag: props.tag ?? '',
    updatedAt: props.updatedAt,
    available: !!props.available,
    icon: props.icon ? props.iconAlias : undefined,
  }
  const parts = []
  parts.push(`  { id: ${JSON.stringify(item.id)}`)
  parts.push(`title: ${JSON.stringify(item.title)}`)
  parts.push(`category: ${JSON.stringify(item.category)}`)
  parts.push(`description: ${JSON.stringify(item.description)}`)
  parts.push(`tag: ${JSON.stringify(item.tag)}`)
  if (item.icon) parts.push(`icon: ${item.icon}`)
  if (item.updatedAt) parts.push(`updatedAt: ${JSON.stringify(item.updatedAt)}`)
  parts.push(`available: ${item.available} },`)
  metaLines.push(parts.join(', '))
}

const out = `${header}import type { DemoCard } from './types'

${iconImports.join('\n')}
${iconImports.length ? '\n' : ''}export type CaseMeta = Omit<DemoCard, 'component'> & { available: boolean }

export const caseLoaders: Record<string, () => Promise<{ default: DemoCard }>> = {
${loaderLines.join('\n')}}

export const demos: CaseMeta[] = [
${metaLines.join('\n')}]
`
writeFileSync(manifestPath, out, 'utf8')
console.log(`[sync-cases] generated ${manifestPath}`)
console.log(`[sync-cases] entries: ${ordered.length}`)
for (const w of warnings) console.log(w)
